name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deploy

    steps:
        
    - name: Generate .env.production File for Production
      run: |
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} > .env.production
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} > .env.production
        echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} > .env.production
        
